name: build diff deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Frontend
        env:
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          ENV: 'production'
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Build Backend
        env:
          QIITA_USER_ID: ${{ secrets.QIITA_USER_ID }}
          QIITA_API_URL: 'https://qiita.com/api/v2'
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          ENV: 'production'
        run: |
          cd backend
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: CDK Diff (PR only)
        if: github.event_name == 'pull_request'
        run: |
          cd infrastructure
          npm ci
          npm run cdk diff

      - name: Deploy CDK stack
        if: github.event_name == 'push'
        env:
          QIITA_USER_ID: ${{ secrets.QIITA_USER_ID }}
          QIITA_API_URL: 'https://qiita.com/api/v2'
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          ENV: 'production'
        run: |
          cd infrastructure
          npm ci
          npm run cdk:deploy:all
